title: Abdul Farah
email: Abdul.n.farah@gmail.com
description: >-
baseurl: ""
url: "http://localhost:4000"
twitter_username: abfarahh
github_username:  abfarah
instagram_username: abfarahh
google_analytics: UA-143619358-1
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock