# Site settings
title: Abdul Farah
description: Abfarah.com
# baseurl: "" # the subpath of your site, e.g. /blog
url: "abfarah.com" 

# User settings
username: Coming Soon!!
user_description: I’m currently a Computer Science student at the University of Minnesota. I love working on challenging projects and learning new things. I was previously a software engineering intern at Target working as a full stack engineer using technologies like react, angular, spring boot, etc. Shoot me an email at abdul.n.farah@gmail.com to get in touch.
user_title: Software Engineer
email: abdul.n.farah@gmail.com
twitter_username: abfarahh
github_username:  abfarah
instagram_username: abfarahh

# Google-analytics
google-analytics:
  id: "UA-143619358-1"

markdown: kramdown

exclude: ['package.json', 'src' , 'node_modules']
